### ISSUE TITLE
`bashlock` seems doesn't work before attach-session

### ISSUE THREAD

**Issue by merryChris** [acornejo/bashlock#3]
I want to lock the clients after `lock-session -t xxx` or `lock-server`. It works on connected clients, but not on the clients attached after locking.

Here are my questions.
- Is this an issue about `bashlock`?
- If yes, how to make `bashlock` support it?
- If no, any way else to make is possible?

Thanks! :）

**Comment by merryChris** [comment]
I read the manpage about `tmux lock-session`, which says 

> Lock all clients attached to target-session.

That is to say it just locks current clients, and leaves attached clients afterwards alone. Isn't it reasonable?

PS: It just works by `bashlock` manually.

**Comment by acornejo** [comment]
This is not a limitation of bashlock, but a limitation on how tmux chose to implementing locking.

See here for a discussion on this https://github.com/tmux/tmux/issues/369

**Comment by merryChris** [comment]
@acornejo Got it, thanks!
